package com.example.createjson

enum class Flags (
    flagName: String,
    defaultValue: Boolean
){
    IS_ADDRESS_LINE_ONE_REQUIRED ("isAddressLineOneRequired", true),
    IS_CITY_REQUIRED ("isCityRequired", true),
    IS_ADDRESS_LINE_TWO_REQUIRED ("isAddressLineTwoRequired", false),
    IS_ADVERTISING_ID_ANALYTICS_ENABLED ("isAdvertisingIdAnalyticsEnabled", false),
    IS_SMART_LINK_ENABLED ("isSmartLinkEnabled", false),
    IS_FB4_ENABLED ("isFb4Enabled", false),//buildConfigWrapper.isBuildTypeDebug),
    IS_SYNC_GENERATION_V2_ENABLE ("isSyncGenerationV2Enable", false),
    IS_POSTAL_CODE_INCLUDED ("isPostalCodeIncluded", true),
    IS_HOME_SCREEN_COACH_MARKS_ENABLED ("isHomeScreenCoachMarksEnabled", true),
    IS_PREFERRED_DEALER_ENABLED ("isPreferredDealerEnabled", true),
    IS_WI_FI_HOT_SPOT_ENABLED ("isWiFiHotspotEnabled", true),
    IS_LOCK_STATUS_ENABLED ("isLockStatusEnabled", true),
    IS_CHANGE_EMAIL_ENABLED ("isChangeEmailEnabled", true),
    IS_FLEET_HEALTH_ENABLED ("isFleetHealthEnabled", true),
    ARE_OILLIFE_PROGNOSTICS_ENABLED ("areOilLifePrognosticsEnabled", false),
    IS_DRSA_ENABLED ("isDrsaEnabled", false),//, buildConfigWrapper.isBuildTypeDebug),
    IS_ZONAL_UNLOCK_ENABLED ("isZonalUnlockEnabled", false),//, buildConfigWrapper.isBuildTypeDebug),
    IS_GUARD_MODE_ENABLED ("isGuardModeEnabled", false),//, buildConfigWrapper.isBuildTypeDebug),
    IS_OSB_PHONE_NUMBER_ENABLED ("isOsbPhoneNumberEnabled", false),//, buildConfigWrapper.isBuildTypeDebug),
    IS_AAR_ENABLED ("isAarEnabled", false),
    IS_DEALER_DETAILS_V2_ENABLED ("isDealerDetailsV2Enabled", true),
    SHOW_ADDRESS_LINE_TWO ("showAddressLineTwo", true),
    SHOW_STATE_OR_COUNTY ("showStateOrCounty", true),
    OPEN_EMAIL_FOR_CONTACT_GUIDE ("openEmailForContactGuide", false),
    SHOULD_HIDE_CONTACT_GUIDE_IN_FORGOT_AND_RESET_PASSWORD ("shouldHideContactGuideInForgotAndResetPassword", false),
    IS_STATE_REQUIRED ("isStateRequired", true),
    IS_OSB_ENABLED ("isOsbEnabled", false),
    IS_MAINTENANCE_SCHEDULE_ENABLED ("isMaintenanceScheduleEnabled", false),
    IS_CHARGING_STATION_SEARCH_ENABLED ("isChargingStationSearchEnabled", false),
    IS_POSTCODE_REQUIRED ("isPostcodeRequired", true),
    SHOW_CITY_OR_TOWN ("showCityOrTown", true),
    SHOW_SUFFIX ("showSuffix", true),
    SHOULD_SHOW_MESSAGE_CENTER_MESSAGE_BODY ("shouldShowMessageCenterMessageBody", false),
    SHOW_FORD_CREDIT_CONFIRMATION_DIALOG ("showFordCreditConfirmationDialog", false),
    IS_TYRE_PRESSURE_HEALTH_DETAILS_ENABLED ("isTyrePressureHealthDetailsEnabled", true),
    IS_COVID19_INFO_ENABLED ("isCOVID19InfoEnabled", false), //getCOVID19InfoUrl.isNotBlank),
    IS_CV_SERVICES_FOR_MARKET_PLACE_ENABLED ("isCVServicesForMarketPlaceEnabled", false),
}